apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sellout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/miguelsdl/sellout-deploy.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sellout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true